# default rules
homepage:
  url:   /
  param: { module: job, action: index }

default_symfony:
  url:   /symfony/:action/*
  param: { module: default }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*

job_show_user:
  url:   /job/:company_slug/:location/:id/:position
  class: sfPropelRoute
  options: { model: JobeetJob, type: object }
  param: { module: job, action: show }
  requirements:
    id: \d+
    sf_method: get #[get] と指定があるが、配列だとwarningがでる
